
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Feb 15 15:30:41 CET 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 42;
  public static final int LEFT_BRACKETS = 35;
  public static final int INCREMENT = 29;
  public static final int CONST = 5;
  public static final int NOT_EQUAL = 21;
  public static final int GREATER = 22;
  public static final int CONTINUE = 14;
  public static final int NUM_CONST = 41;
  public static final int LESS = 24;
  public static final int MINUS = 16;
  public static final int DECREMENT = 30;
  public static final int LEFT_BRACES = 37;
  public static final int SEMICOLON = 31;
  public static final int COMMA = 32;
  public static final int DIV = 18;
  public static final int QUESTION_MARK = 39;
  public static final int RIGHT_PARENTHESIS = 34;
  public static final int LESS_EQUAL = 25;
  public static final int PLUS = 15;
  public static final int ASSIGN = 28;
  public static final int IF = 6;
  public static final int IDENTIFICATOR = 44;
  public static final int RIGHT_BRACES = 38;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int EQUAL = 20;
  public static final int LOGICAL_OR = 27;
  public static final int GREATER_EQUAL = 23;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 17;
  public static final int MOD = 19;
  public static final int BREAK = 3;
  public static final int VOID = 13;
  public static final int RIGHT_BRACKETS = 36;
  public static final int COLON = 40;
  public static final int ELSE = 4;
  public static final int READ = 11;
  public static final int WHILE = 8;
  public static final int LOGICAL_AND = 26;
  public static final int BOOL_CONST = 43;
  public static final int PRINT = 10;
  public static final int LEFT_PARENTHESIS = 33;
  public static final int DO = 7;
}

